# Default values for uptime-kuma using helmlet library chart.

replicaCount: 1

image:
  repository: "louislam/uptime-kuma"
  pullPolicy: IfNotPresent
  tag: "1.23.13-debian"

imagePullSecrets: []

configMap: {}
serviceAccount: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
secret: {}
service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /manifest.json
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manifest.json
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  mountPath: /app/data
  volumeName: data

additionalVolumes: []
additionalVolumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}