apiVersion: v2
name: helmlet
description: A Helm Library Chart for Kubernetes deployments
type: library
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - deployment
  - service
  - ingress
  - library

maintainers:
  - name: Ole Kleinschmidt

sources:
  - https://datenreisende.github.io/charts/helmlet/

dependencies: []