{{- define "helmlet.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmlet.fullname" . }}
  labels:
    {{- include "helmlet.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end -}}