{{- define "helmlet.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmlet.fullname" . }}
  labels:
    {{- include "helmlet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.data }}
  {{- toYaml .Values.secret.data | nindent 2 }}
  {{- end }}
  {{- if .Values.secret.stringData }}
  {{- toYaml .Values.secret.stringData | nindent 2 }}
  {{- end }}
{{- end -}}