name: Deploy Helm Chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.0'

      - name: Package Helm charts
        run: |
          helm package ./charts/uptime-kuma -d ./charts

      - name: Publish Helm charts to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          echo ${{ vars.ACTION_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
          helm push charts/uptime-kuma-*.tgz oci://ghcr.io/datenreisende/charts/