name: Deploy Helm Chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.0'

      - name: Identify Changed Charts
        id: changed_charts
        run: |
          # Find all charts that have changed since the last commit to main
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep 'charts/' | cut -d '/' -f2 | uniq)
          echo "Changed charts: $CHANGED_DIRS"
          echo "::set-output name=changed_dirs::$CHANGED_DIRS"

      - name: Package and Publish Helm charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_SECRET: ${{ secrets.REGISTRY_SECRET }}
        run: |
          for chart in ${{ steps.changed_charts.outputs.changed_dirs }}; do
            echo "Packaging and pushing $chart..."
            helm package ./charts/$chart -d ./charts
            echo $REGISTRY_SECRET | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
            helm push ./charts/${chart}-*.tgz oci://ghcr.io/datenreisende/charts/
          done
        if: ${{ steps.changed_charts.outputs.changed_dirs != '' }}