name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write # publish chart to gh-pages branch
  packages: write # publish chart to ghcr.io

jobs:
  release-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      # Publish OCI charts to ghcr.io
      - name: Generate charts
        run: |
          mkdir -p .cr-release-packages
          for d in charts/* ; do
            helm package "$d" --destination .cr-release-packages
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Publish Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            echo ${pkg}
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/datenreisende/charts
          done

  release-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      # Publish charts to gh-pages branch
      - name: Publish charts to GitHub Pages
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: .github/configs/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.REGISTRY_SECRET }}"

  update-readme:
    runs-on: ubuntu-latest
    needs: release-ghcr
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Generate Helm Charts Table
        run: |
          echo "| Chart Name | Version |" > charts-table.txt
          echo "|------------|---------|" >> charts-table.txt
          for d in charts/* ; do
            chart_name=$(basename "$d")
            chart_version=$(helm show chart "$d" | grep '^version:' | awk '{print $2}')
            echo "| $chart_name | $chart_version |" >> charts-table.txt
          done

      - name: Append Table to README
        run: |
          echo "\n## Available Charts\n" >> README.md
          cat charts-table.txt >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "docs: update README with Helm charts table"
          git push