name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-helmlet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      - name: Update Helm Repository and Cache
        run: |
          helm repo add datenreisende https://datenreisende.github.io/charts/
          helm repo update

      - name: Update helmlet Chart Dependencies
        run: |
          helm dependency update charts/helmlet

      - name: Package helmlet Chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/helmlet --destination .cr-release-packages

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Publish helmlet Chart to GHCR
        run: |
          helm push .cr-release-packages/helmlet-*.tgz oci://ghcr.io/datenreisende/charts

  release-other-charts:
    runs-on: ubuntu-latest
    needs: release-helmlet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      - name: Update Helm Repository and Cache
        run: |
          helm repo add datenreisende https://datenreisende.github.io/charts/
          helm repo update

      # Update dependencies for all other charts
      - name: Update All Other Chart Dependencies
        run: |
          for d in charts/* ; do
            if [[ "$d" != "charts/helmlet" ]]; then
              helm dependency update "$d"
            fi
          done

      # Package all other charts
      - name: Generate charts
        run: |
          mkdir -p .cr-release-packages
          for d in charts/* ; do
            if [[ "$d" != "charts/helmlet" ]]; then
              helm package "$d" --destination .cr-release-packages
            fi
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Publish Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [[ "$pkg" != *"helmlet"* ]]; then
              helm push "${pkg}" oci://ghcr.io/datenreisende/charts
            fi
          done

  release-gh-pages:
    runs-on: ubuntu-latest
    needs: release-other-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      - name: Update Helm Repository and Cache
        run: |
          helm repo add datenreisende https://datenreisende.github.io/charts/
          helm repo update

      - name: Update Chart Dependencies for All Charts
        run: |
          for d in charts/* ; do
            helm dependency update "$d"
          done

      # Publish charts to gh-pages branch
      - name: Publish charts to GitHub Pages
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: .github/configs/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.REGISTRY_SECRET }}"

  update-readme:
    runs-on: ubuntu-latest
    needs: release-other-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Remove existing Helm Charts Table
        run: |
          awk '/## Available Helm Charts/{flag=1} /## /{flag=0} !flag' README.md > README.tmp && mv README.tmp README.md

      - name: Generate Helm Charts Table
        run: |
          echo "| Chart Name | Version | Type |" > charts-table.txt
          echo "|------------|---------|------|" >> charts-table.txt
          for d in charts/* ; do
            chart_name=$(basename "$d")
            chart_version=$(helm show chart "$d" | grep '^version:' | awk '{print $2}')
            chart_type=$(helm show chart "$d" | grep '^type:' | awk '{print $2}')
            if [ -z "$chart_type" ]; then
              chart_type="Application" # Default type if not specified
            fi
            echo "| $chart_name | $chart_version | $chart_type |" >> charts-table.txt
          done

      - name: Insert Table into README
        run: |
          echo "## Available Helm Charts" > charts-section.txt
          echo "" >> charts-section.txt
          cat charts-table.txt >> charts-section.txt
          
          awk '/## How to Add This Repository/{flag=1; if(!flag2){print ""; system("cat charts-section.txt"); flag2=1}} 1' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "docs: update README with Helm charts table including chart type"
          git push